# Generated by Django 5.0.2 on 2024-03-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
